# Research data supporting "Practical and improved density functionals for computational catalysis on metal surfaces"

This notebook accompanies our paper: **Practical and improved density functionals for computational catalysis on metal surfaces**. It can be found on GitHub at https://github.com/benshi97/Data_NSCDFT_for_Metals and explored interactively on [Colab](https://colab.research.google.com/github/benshi97/Data_NSCDFT_for_Metals/blob/main/analyse.ipynb).

### Abstract

Density functional theory (DFT) has been critical towards our current atomistic understanding of catalysis on transition-metal surfaces.
It has opened new paradigms in rational catalyst design, predicting fundamental properties, like the adsorption energy and reaction barriers, linked to catalytic performance.
However, such applications depend sensitively on the predictive accuracy of DFT and achieving experimental-level reliability, so-called transition-metal chemical accuracy (13 kJ/mol), remains challenging for present density functional approximations (DFAs) or even methods beyond DFT.
We introduce a new framework for designing DFAs tailored towards studying molecules adsorbed on transition-metal surfaces, building upon recent developments in non-self-consistent DFAs.
We propose two functionals within this framework, demonstrating that transition-metal chemical accuracy can be achieved across a diverse set of 39 adsorption reactions while delivering consistent performance for 17 barrier heights.
Moreover, we show that these non-self-consistent DFAs address qualitative failures that challenge current self-consistent DFAs, such as CO adsorption on Pt(111) and graphene on Ni(111).
The resulting functionals are computationally practical and compatible with existing DFT codes, with scripts and workflows provided to use them.
Looking ahead, this framework establishes a path toward developing more accurate and sophisticated DFAs for computational heterogeneous catalysis and beyond.

## Table of Contents

1. [Lattice energies of X23 dataset](#lattice-energies-of-x23-dataset)
2. [Analysis DMC costs](#analysis-dmc-costs)
3. [Lattice and relative energies of ICE13](#lattice-and-relative-energies-of-ice13)
4. [Optimizing B86bPBE50-revXDM](#optimizing-b86bpbe50-revxdm)
5. [Relative energies of pharmaceutical polymorphs](#relative-energies-of-pharmaceutical-polymorphs)
6. [DFT Benchmarks](#dft-benchmarks)

In [2]:
# Check if we are in Google Colab environment
try:
    import google.colab
    IN_COLAB = True
    usetex = False
    import os
    import subprocess
    import sys
    def pip_install(pkg):
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "--quiet", pkg],
            check=True
        )

    pip_install("ase")
except:
    import os
    IN_COLAB = False
    if os.path.expanduser('~') == '/Users/bshi':
        usetex = True
    else:
        usetex = False

if usetex:
    def textbf(text):
        return r'\textbf{' + text + '}'
else:
    def textbf(text):
        return text

# If in Google Colab, install the necessary data and set up the necessary environment
if IN_COLAB == True:
    repo_url = "https://github.com/benshi97/Data_NSCDFT_for_Metals"

    # Clone the repository
    %cd /content
    !rm -rf /content/Data_LNOMBECC
    !git clone {repo_url}
    %cd /content/Data_LNOMBECC

replot_analysis = False

# Import necessary functions
from Scripts.analysis_scripts import *
from Scripts.plot_scripts import *

if usetex == True:
    textrue_import()
else:
    texfalse_import()

# CE39 dataset

## Experimental data

In [3]:
raw_data = { # Taken from Surf. Sci. 640, 36–44 (2015).
    "#": list(range(1, 40)),
    "Surface reaction": [
        "CO + Ni(111) → CO/Ni(111)",
        "CO + Pt(111) → CO/Pt(111)",
        "CO + Pd(111) → CO/Pd(111)",
        "CO + Pd(100) → CO/Pd(100)",
        "CO + Rh(111) → CO/Rh(111)",
        "CO + Ir(111) → CO/Ir(111)",
        "CO + Cu(111) → CO/Cu(111)",
        "CO + Ru(001) → CO/Ru(001)",
        "CO + Co(001) → CO/Co(001)",
        "NO + Ni(100) → N/Ni(100) + O/Ni(100)",
        "NO + Pt(111) → NO/Pt(111)",
        "NO + Pd(111) → NO/Pd(111)",
        "NO + Pd(100) → NO/Pd(100)",
        "O2 + Ni(111) → 2O/Ni(111)",
        "O2 + Ni(100) → 2O/Ni(100)",
        "O2 + Pt(111) → 2O/Pt(111)",
        "O2 + Rh(100) → 2O/Rh(100)",
        "H2 + Pt(111) → 2H/Pt(111)",
        "H2 + Ni(111) → 2H/Ni(111)",
        "H2 + Ni(100) → 2H/Ni(100)",
        "H2 + Rh(111) → 2H/Rh(111)",
        "H2 + Pd(111) → 2H/Pd(111)",
        "I2 + Pt(111) → 2I/Pt(111)",
        "CH2I2 + Pt(111) → CH/Pt(111) + H/Pt(111) + 2I/Pt(111)",
        "CH3I + Pt(111) → CH3/Pt(111) + I/Pt(111)",
        "NH3 + Cu(100) → NH3/Cu(100)",
        "CH3I + Pt(111) → CH3I/Pt(111)",
        "CH3OH + Pt(111) → CH3OH/Pt(111)",
        "CH4 + Pt(111) → CH4/Pt(111)",
        "C2H6 + Pt(111) → C2H6/Pt(111)",
        "C3H8 + Pt(111) → C3H8/Pt(111)",
        "C4H10 + Pt(111) → C4H10/Pt(111)",
        "C6H6 + Pt(111) → C6H6/Pt(111)",
        "C6H6 + Cu(111) → C6H6/Cu(111)",
        "C6H6 + Ag(111) → C6H6/Ag(111)",
        "C6H6 + Au(111) → C6H6/Au(111)",
        "C6H10 + Pt(111) → C6H10/Pt(111)",
        "H2O + Pt(111) → H2O/Pt(111)",
        "H2O + OPt(111) → H2OOH/Pt(111)"
    ],
    "Coverage (ML)": [
        "1/4", "1/4", "1/4", "1/4", "1/4", "1/4", "1/4", "1/4", "1/4", "1/8", "1/4", "1/4", "1/4", "1/8",
        "1/8", "1/18", "1/8", "1/8", "1/8", "1/8", "1/8", "1/8", "1/4", "1/4", "1/4", "1/4", "1/4",
        "1/4", "1/4", "1/9", "1/9", "1/9", "1/9", "1/9", "1/9", "1/9", "1/9", "1/4", "1/2"
    ],
    "Reaction enthalpy (kJ/mol)": [
        -122, -120, -143, -155, -139, -158, -53, -158, -115, -290, -114, -179, -161, -480,
        -530, -208, -358, -72, -94, -94, -70, -88, -312, -473, -212, -57, -84.5, -56, -15,
        -28.5, -41.3, -50.8, -164, -68, -63, -72, -122, -51.3, -57.4
    ],
    "Temp. (K)": [
        350, 340, 450, 430, 500, 420, 350, 475, 370, 300, 300, 520, 300, 300,
        300, 515, 300, 300, 370, 370, 325, 370, 0, 210, 320, 235, 100, 100,
        63, 106, 139, 171, 300, 225, 210, 230, 100, 120, 150
    ],
    "Reaction energy (kJ/mol)": [
        -119, -117, -139, -151, -135, -154, -52, -154, -112, -288, -112, -175, -159, -479,
        -528, -204, -356, -70, -91, -91, -67, -85, -230, -471, -209, -55, -83.7, -55,
        -14.5, -27.6, -40.1, -49.4, -300, -66, -61, -70, -121, -50.3, -56.2
    ],
    "Reaction energy without ZPE (kJ/mol)": [
        -124, -124, -144, -157, -142, -164, -57, -161, -119, -299,
        -119, -182, -163, -485, -530, -208, -355, -72, -100, -87,
        -72, -90, -313, -455, -209
    ] + [
        -60, -84, -55, -14, -27, -39, -48, -162, -66, -61,
        -70, -123, -55, -66
    ],
    "Weight": [ 1, 1, 1, 1, 1, 1, 1, 1, 1,0.5, 1, 1, 1, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,0.5, 0.5, 0.5, 0.5, 0.25, 0.5] + [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,1]
}

ce39_dataset_dict = {}

calc_molecule_list = []
calc_molecule_surface_list = []

for ce39_idx in range(39):


    if 'Co' in raw_data['Surface reaction'][ce39_idx] or 'Ru' in raw_data['Surface reaction'][ce39_idx]:
        crystal_type = 'hcp'
    else:
        crystal_type = 'fcc'

    # Set the supercell_size based on coverage
    if raw_data['Coverage (ML)'][ce39_idx] in ['1/4','1/8']:
        surface_sc_size = '2x2'
    else:
        surface_sc_size = '3x3'

    surface_type = raw_data['Surface reaction'][ce39_idx].split()[2].replace('(',f'_{crystal_type}_').replace(')',f'_{surface_sc_size}')
    system_molecule = raw_data['Surface reaction'][ce39_idx].split()[0]
    molecule_surface_system_list = []
    for molecule_surface_system in raw_data['Surface reaction'][ce39_idx].split('→')[1].split('+'):
        if molecule_surface_system.strip()[0].isdigit():
            molecule_surface_system_list += [molecule_surface_system.strip()[1:].replace('/','-').replace('(',f'_{crystal_type}_').replace(')',f'_{surface_sc_size}')]*int(molecule_surface_system.strip()[0])
        else:
            molecule_surface_system_list += [molecule_surface_system.strip().replace('/','-').replace('(',f'_{crystal_type}_').replace(')',f'_{surface_sc_size}')]


    ce39_dataset_dict[f'{ce39_idx+1:02d}'] = {'Reaction': raw_data['Surface reaction'][ce39_idx], 'MAD Weight': raw_data['Weight'][ce39_idx], 'Reactant Molecule': [system_molecule], 'Reactant Surface': [surface_type], 'Products': molecule_surface_system_list, 'Reaction Enthalpy': int(raw_data["Reaction enthalpy (kJ/mol)"][ce39_idx]), 'Reaction Energy': int(raw_data["Reaction energy (kJ/mol)"][ce39_idx]),'Reaction Energy without ZPE': int(raw_data["Reaction energy without ZPE (kJ/mol)"][ce39_idx])}

    for molecule_surface_system in molecule_surface_system_list:
        if molecule_surface_system not in calc_molecule_surface_list:
            calc_molecule_surface_list += [molecule_surface_system]
    
    if system_molecule not in calc_molecule_list:
        calc_molecule_list += [system_molecule]

ce39_dataset_df = pd.DataFrame.from_dict(ce39_dataset_dict, orient='index')
display(ce39_dataset_df)

,Reaction,MAD Weight,Reactant Molecule,Reactant Surface,Products,Reaction Enthalpy,Reaction Energy,Reaction Energy without ZPE
01,CO + Ni(111) → CO/Ni(111),1.00,[CO],[Ni_fcc_111_2x2],[CO-Ni_fcc_111_2x2],-122,-119,-124
02,CO + Pt(111) → CO/Pt(111),1.00,[CO],[Pt_fcc_111_2x2],[CO-Pt_fcc_111_2x2],-120,-117,-124
03,CO + Pd(111) → CO/Pd(111),1.00,[CO],[Pd_fcc_111_2x2],[CO-Pd_fcc_111_2x2],-143,-139,-144
04,CO + Pd(100) → CO/Pd(100),1.00,[CO],[Pd_fcc_100_2x2],[CO-Pd_fcc_100_2x2],-155,-151,-157
05,CO + Rh(111) → CO/Rh(111),1.00,[CO],[Rh_fcc_111_2x2],[CO-Rh_fcc_111_2x2],-139,-135,-142
06,CO + Ir(111) → CO/Ir(111),1.00,[CO],[Ir_fcc_111_2x2],[CO-Ir_fcc_111_2x2],-158,-154,-164
07,CO + Cu(111) → CO/Cu(111),1.00,[CO],[Cu_fcc_111_2x2],[CO-Cu_fcc_111_2x2],-53,-52,-57
08,CO + Ru(001) → CO/Ru(001),1.00,[CO],[Ru_hcp_001_2x2],[CO-Ru_hcp_001_2x2],-158,-154,-161
09,CO + Co(001) → CO/Co(001),1.00,[CO],[Co_hcp_001_2x2],[CO-Co_hcp_001_2x2],-115,-112,-119
10,NO + Ni(100) → N/Ni(100) + O/Ni(100),0.50,[NO],[Ni_fcc_100_2x2],"[N-Ni_fcc_100_2x2, O-Ni_fcc_100_2x2]",-290,-288,-299
11,NO + Pt(111) → NO/Pt(111),1.00,[NO],[Pt_fcc_111_2x2],[NO-Pt_fcc_111_2x2],-114,-112,-119
12,NO + Pd(111) → NO/Pd(111),1.00,[NO],[Pd_fcc_111_2x2],[NO-Pd_fcc_111_2x2],-179,-175,-182
13,NO + Pd(100) → NO/Pd(100),1.00,[NO],[Pd_fcc_100_2x2],[NO-Pd_fcc_100_2x2],-161,-159,-163
14,O2 + Ni(111) → 2O/Ni(111),0.50,[O2],[Ni_fcc_111_2x2],"[O-Ni_fcc_111_2x2, O-Ni_fcc_111_2x2]",-480,-479,-485
15,O2 + Ni(100) → 2O/Ni(100),0.50,[O2],[Ni_fcc_100_2x2],"[O-Ni_fcc_100_2x2, O-Ni_fcc_100_2x2]",-530,-528,-530
16,O2 + Pt(111) → 2O/Pt(111),0.50,[O2],[Pt_fcc_111_3x3],"[O-Pt_fcc_111_3x3, O-Pt_fcc_111_3x3]",-208,-204,-208
17,O2 + Rh(100) → 2O/Rh(100),0.50,[O2],[Rh_fcc_100_2x2],"[O-Rh_fcc_100_2x2, O-Rh_fcc_100_2x2]",-358,-356,-355
18,H2 + Pt(111) → 2H/Pt(111),0.50,[H2],[Pt_fcc_111_2x2],"[H-Pt_fcc_111_2x2, H-Pt_fcc_111_2x2]",-72,-70,-72
19,H2 + Ni(111) → 2H/Ni(111),0.50,[H2],[Ni_fcc_111_2x2],"[H-Ni_fcc_111_2x2, H-Ni_fcc_111_2x2]",-94,-91,-100
20,H2 + Ni(100) → 2H/Ni(100),0.50,[H2],[Ni_fcc_100_2x2],"[H-Ni_fcc_100_2x2, H-Ni_fcc_100_2x2]",-94,-91,-87
21,H2 + Rh(111) → 2H/Rh(111),0.50,[H2],[Rh_fcc_111_2x2],"[H-Rh_fcc_111_2x2, H-Rh_fcc_111_2x2]",-70,-67,-72
22,H2 + Pd(111) → 2H/Pd(111),0.50,[H2],[Pd_fcc_111_2x2],"[H-Pd_fcc_111_2x2, H-Pd_fcc_111_2x2]",-88,-85,-90
23,I2 + Pt(111) → 2I/Pt(111),0.50,[I2],[Pt_fcc_111_2x2],"[I-Pt_fcc_111_2x2, I-Pt_fcc_111_2x2]",-312,-230,-313
24,CH2I2 + Pt(111) → CH/Pt(111) + H/Pt(111) + 2I/...,0.25,[CH2I2],[Pt_fcc_111_2x2],"[CH-Pt_fcc_111_2x2, H-Pt_fcc_111_2x2, I-Pt_fcc...",-473,-471,-455
25,CH3I + Pt(111) → CH3/Pt(111) + I/Pt(111),0.50,[CH3I],[Pt_fcc_111_2x2],"[CH3-Pt_fcc_111_2x2, I-Pt_fcc_111_2x2]",-212,-209,-209
26,NH3 + Cu(100) → NH3/Cu(100),1.00,[NH3],[Cu_fcc_100_2x2],[NH3-Cu_fcc_100_2x2],-57,-55,-60
27,CH3I + Pt(111) → CH3I/Pt(111),1.00,[CH3I],[Pt_fcc_111_2x2],[CH3I-Pt_fcc_111_2x2],-84,-83,-84
28,CH3OH + Pt(111) → CH3OH/Pt(111),1.00,[CH3OH],[Pt_fcc_111_2x2],[CH3OH-Pt_fcc_111_2x2],-56,-55,-55
29,CH4 + Pt(111) → CH4/Pt(111),1.00,[CH4],[Pt_fcc_111_2x2],[CH4-Pt_fcc_111_2x2],-15,-14,-14
30,C2H6 + Pt(111) → C2H6/Pt(111),1.00,[C2H6],[Pt_fcc_111_3x3],[C2H6-Pt_fcc_111_3x3],-28,-27,-27
31,C3H8 + Pt(111) → C3H8/Pt(111),1.00,[C3H8],[Pt_fcc_111_3x3],[C3H8-Pt_fcc_111_3x3],-41,-40,-39
32,C4H10 + Pt(111) → C4H10/Pt(111),1.00,[C4H10],[Pt_fcc_111_3x3],[C4H10-Pt_fcc_111_3x3],-50,-49,-48
33,C6H6 + Pt(111) → C6H6/Pt(111),1.00,[C6H6],[Pt_fcc_111_3x3],[C6H6-Pt_fcc_111_3x3],-164,-300,-162
34,C6H6 + Cu(111) → C6H6/Cu(111),1.00,[C6H6],[Cu_fcc_111_3x3],[C6H6-Cu_fcc_111_3x3],-68,-66,-66
35,C6H6 + Ag(111) → C6H6/Ag(111),1.00,[C6H6],[Ag_fcc_111_3x3],[C6H6-Ag_fcc_111_3x3],-63,-61,-61
36,C6H6 + Au(111) → C6H6/Au(111),1.00,[C6H6],[Au_fcc_111_3x3],[C6H6-Au_fcc_111_3x3],-72,-70,-70
37,C6H10 + Pt(111) → C6H10/Pt(111),1.00,[C6H10],[Pt_fcc_111_3x3],[C6H10-Pt_fcc_111_3x3],-122,-121,-123
38,H2O + Pt(111) → H2O/Pt(111),1.00,[H2O],[Pt_fcc_111_2x2],[H2O-Pt_fcc_111_2x2],-51,-50,-55
39,H2O + OPt(111) → H2OOH/Pt(111),1.00,[H2O],[OPt_fcc_111_3x3],[H2OOH-Pt_fcc_111_3x3],-57,-56,-66

## DFT estimates

### BEEF-vdW

In [4]:
# Calculate the adsorption energy from BEEF-vdW with a 4L and 6L slab
vasp_method = 'vasp'

ce39_eads_dict = {ce39_idx: {'Reaction': '', 'Experiment': 0, 'BEEFvdW (4L)': 0, 'BEEFvdW (6L)': 0} for ce39_idx in ce39_dataset_dict}

for method in ['4L','6L']:
    if method == '4L':
        root_folder = f'Data/CE39/Eads_BF_4L'
    elif method == '6L':
        root_folder = f'Data/CE39/Eads_BF_6L'

    for ce39_idx in ce39_dataset_dict:
        try:
            reactant_molecule = ce39_dataset_dict[ce39_idx]['Reactant Molecule'][0]
            reactant_surface = ce39_dataset_dict[ce39_idx]['Reactant Surface'][0]
            products = ce39_dataset_dict[ce39_idx]['Products']
            sc_size = products[0].split('_')[-1]  # Extract the supercell size from the first product
            num_products = len(products)

            total_product_energy = 0
            for product_idx in range(num_products):
                total_product_energy += get_energy(f'{root_folder}/Molecule-Surface/{method}_{products[product_idx]}/OUTCAR.gz', code='vasp')

            if 'H2OOH' not in ce39_dataset_dict[ce39_idx]['Reaction']:
                reactant_molecule_energy = get_energy(f'{root_folder}/Molecule/{reactant_molecule}/OUTCAR.gz', code='vasp')
                reactant_surface_energy = get_energy(f'{root_folder}/Surface/{method}_{reactant_surface}/OUTCAR.gz', code='vasp')
                ce39_eads_dict[ce39_idx][f'BEEFvdW ({method})'] = (total_product_energy - reactant_molecule_energy - num_products * reactant_surface_energy) * 1000 / kjmol_to_meV
            else:
                reactant_molecule_energy = get_energy(f'{root_folder}/Molecule/{reactant_molecule}/OUTCAR.gz', code='vasp')
                reactant_surface_energy = (1/3)*get_energy(f'{root_folder}/Molecule-Surface/{method}_O-Pt_fcc_111_{sc_size}/OUTCAR.gz', code='vasp')  - (1/9)*get_energy(f'{root_folder}/Surface/{method}_Pt_fcc_111_{sc_size}/OUTCAR.gz', code='vasp') 
                ce39_eads_dict[ce39_idx][f'BEEFvdW ({method})'] = (2 / 9 * total_product_energy - reactant_molecule_energy - reactant_surface_energy) * 1000 / kjmol_to_meV

            ce39_eads_dict[ce39_idx]['Experiment'] = ce39_dataset_dict[ce39_idx]['Reaction Energy without ZPE']
            ce39_eads_dict[ce39_idx]['Reaction'] = ce39_dataset_dict[ce39_idx]['Reaction']
        except:
            print(f"Error processing reaction {ce39_idx}: {ce39_dataset_dict[ce39_idx]['Reaction']}")
            continue
# Convert to DataFrame
ce39_eads_df = pd.DataFrame.from_dict(ce39_eads_dict, orient='index')
mad_dict = {method: np.mean(abs(ce39_eads_df[method] - ce39_eads_df['Experiment']) * ce39_dataset_df['MAD Weight']) for method in ['BEEFvdW (4L)', 'BEEFvdW (6L)']}
# Add an additional row at the bottom that is the MAD for each method
ce39_eads_df.loc['MAD'] = ['MAD', 0, mad_dict['BEEFvdW (4L)'], mad_dict['BEEFvdW (6L)']]

# Round to nearest integer and convert to integer
ce39_eads_df = ce39_eads_df.round(0).astype({'Experiment': 'Int64', 'BEEFvdW (4L)': 'Int64', 'BEEFvdW (6L)': 'Int64', 'Reaction': str}) 

display(ce39_eads_df)

,Reaction,Experiment,BEEFvdW (4L),BEEFvdW (6L)
01,CO + Ni(111) → CO/Ni(111),-124,-150,-151
02,CO + Pt(111) → CO/Pt(111),-124,-133,-135
03,CO + Pd(111) → CO/Pd(111),-144,-158,-148
04,CO + Pd(100) → CO/Pd(100),-157,-152,-150
05,CO + Rh(111) → CO/Rh(111),-142,-161,-163
06,CO + Ir(111) → CO/Ir(111),-164,-172,-179
07,CO + Cu(111) → CO/Cu(111),-57,-52,-50
08,CO + Ru(001) → CO/Ru(001),-161,-162,-156
09,CO + Co(001) → CO/Co(001),-119,-135,-137
10,NO + Ni(100) → N/Ni(100) + O/Ni(100),-299,-393,-385
11,NO + Pt(111) → NO/Pt(111),-119,-150,-156
12,NO + Pd(111) → NO/Pd(111),-182,-189,-190
13,NO + Pd(100) → NO/Pd(100),-163,-172,-173
14,O2 + Ni(111) → 2O/Ni(111),-485,-433,-430
15,O2 + Ni(100) → 2O/Ni(100),-530,-482,-476
16,O2 + Pt(111) → 2O/Pt(111),-208,-192,-208
17,O2 + Rh(100) → 2O/Rh(100),-355,-395,-366
18,H2 + Pt(111) → 2H/Pt(111),-72,-41,-48
19,H2 + Ni(111) → 2H/Ni(111),-100,-67,-66
20,H2 + Ni(100) → 2H/Ni(100),-87,-55,-53
21,H2 + Rh(111) → 2H/Rh(111),-72,-58,-58
22,H2 + Pd(111) → 2H/Pd(111),-90,-63,-39
23,I2 + Pt(111) → 2I/Pt(111),-313,-269,-282
24,CH2I2 + Pt(111) → CH/Pt(111) + H/Pt(111) + 2I/...,-455,-334,-356
25,CH3I + Pt(111) → CH3/Pt(111) + I/Pt(111),-209,-161,-172
26,NH3 + Cu(100) → NH3/Cu(100),-60,-37,-35
27,CH3I + Pt(111) → CH3I/Pt(111),-84,-62,-63
28,CH3OH + Pt(111) → CH3OH/Pt(111),-55,-33,-33
29,CH4 + Pt(111) → CH4/Pt(111),-14,-16,-16
30,C2H6 + Pt(111) → C2H6/Pt(111),-27,-15,-22
31,C3H8 + Pt(111) → C3H8/Pt(111),-39,-30,-30
32,C4H10 + Pt(111) → C4H10/Pt(111),-48,-40,-40
33,C6H6 + Pt(111) → C6H6/Pt(111),-162,-74,-89
34,C6H6 + Cu(111) → C6H6/Cu(111),-66,-40,-40
35,C6H6 + Ag(111) → C6H6/Ag(111),-61,-35,-36
36,C6H6 + Au(111) → C6H6/Au(111),-70,-41,-42
37,C6H10 + Pt(111) → C6H10/Pt(111),-123,-77,-88
38,H2O + Pt(111) → H2O/Pt(111),-55,-22,-22
39,H2O + OPt(111) → H2OOH/Pt(111),-66,-54,-55
MAD,MAD,0,20,19