# Research data supporting "Practical and improved density functionals for computational catalysis on metal surfaces"

This notebook accompanies our paper: **Practical and improved density functionals for computational catalysis on metal surfaces**. It can be found on GitHub at https://github.com/benshi97/Data_NSCDFT_for_Metals and explored interactively on [Colab](https://colab.research.google.com/github/benshi97/Data_NSCDFT_for_Metals/blob/main/analyse.ipynb).

### Abstract

Density functional theory (DFT) has been critical towards our current atomistic understanding of catalysis on transition-metal surfaces.
It has opened new paradigms in rational catalyst design, predicting fundamental properties, like the adsorption energy and reaction barriers, linked to catalytic performance.
However, such applications depend sensitively on the predictive accuracy of DFT and achieving experimental-level reliability, so-called transition-metal chemical accuracy (13 kJ/mol), remains challenging for present density functional approximations (DFAs) or even methods beyond DFT.
We introduce a new framework for designing DFAs tailored towards studying molecules adsorbed on transition-metal surfaces, building upon recent developments in non-self-consistent DFAs.
We propose two functionals within this framework, demonstrating that transition-metal chemical accuracy can be achieved across a diverse set of 39 adsorption reactions while delivering consistent performance for 17 barrier heights.
Moreover, we show that these non-self-consistent DFAs address qualitative failures that challenge current self-consistent DFAs, such as CO adsorption on Pt(111) and graphene on Ni(111).
The resulting functionals are computationally practical and compatible with existing DFT codes, with scripts and workflows provided to use them.
Looking ahead, this framework establishes a path toward developing more accurate and sophisticated DFAs for computational heterogeneous catalysis and beyond.

## Table of Contents

1. [Lattice energies of X23 dataset](#lattice-energies-of-x23-dataset)
2. [Analysis DMC costs](#analysis-dmc-costs)
3. [Lattice and relative energies of ICE13](#lattice-and-relative-energies-of-ice13)
4. [Optimizing B86bPBE50-revXDM](#optimizing-b86bpbe50-revxdm)
5. [Relative energies of pharmaceutical polymorphs](#relative-energies-of-pharmaceutical-polymorphs)
6. [DFT Benchmarks](#dft-benchmarks)

In [5]:
# Check if we are in Google Colab environment
try:
    import google.colab
    IN_COLAB = True
    usetex = False
    import os
    import subprocess
    import sys
except:
    import os
    IN_COLAB = False
    if os.path.expanduser('~') == '/Users/bshi':
        usetex = True
    else:
        usetex = False

if usetex:
    def textbf(text):
        return r'\textbf{' + text + '}'
else:
    def textbf(text):
        return text

# If in Google Colab, install the necessary data and set up the necessary environment
if IN_COLAB == True:
    repo_url = "https://github.com/benshi97/Data_NSCDFT_for_Metals"

    # Clone the repository
    %cd /content
    !rm -rf /content/Data_LNOMBECC
    !git clone {repo_url}
    %cd /content/Data_LNOMBECC

replot_analysis = False

# Import necessary functions
from Scripts.analysis_scripts import *
from Scripts.plot_scripts import *

if usetex == True:
    textrue_import()
else:
    texfalse_import()

dft_xc_list = [
    "01_PBE",
    "02_PBEsol",
    "03_RPBE",
    "04_revPBE",
    "05_BLYP",
    "06_r2SCAN",
    "07_MS2",
    "08_revTPSS",
    "09_PBED3",
    "10_PBEDDsC",
    "11_RPBED3",
    "12_optPBEvdW",
    "13_revvdWDF2",
    "14_r2SCANrVV10"
]

method_dict = {
    '01_PBE': {'label': 'PBE', 'color': 'orange'},
    '02_PBEsol': {'label': 'PBEsol', 'color': 'purple'},
    '03_RPBE': {'label': 'RPBE', 'color': 'cyan'},
    '04_revPBE': {'label': 'revPBE', 'color': 'magenta'},
    '05_BLYP': {'label': 'BLYP', 'color': 'lime'},
    '06_r2SCAN': {'label': r'r$^2$SCAN', 'color': 'pink'},
    '07_MS2': {'label': 'MS2', 'color': 'teal'},
    '08_revTPSS': {'label': 'revTPSS', 'color': 'lavendar'},
    '09_PBED3': {'label': 'PBE-D3', 'color': 'brown'},
    '10_PBEDDsC': {'label': 'PBE-DdsC', 'color': 'beige'},
    '11_RPBED3': {'label': 'RPBE-D3', 'color': 'maroon'},
    '12_optPBEvdW': {'label': 'optPBE-vdW', 'color': 'apricot'},
    '13_revvdWDF2': {'label': 'revvdW-DF2', 'color': 'navy'},
    '14_r2SCANrVV10': {'label': r'r$^2$SCAN+rVV10', 'color': 'olive'},
    'RPA': {'label': 'RPA@PBE', 'color': 'blue'},
    'BEEFvdW': {'label': 'BEEF-vdW', 'color': 'red'},
    'hBEEFvdW': {'label': 'hBEEF-vdW', 'color': 'green'},
    'dhBEEFvdW': {'label': 'dhBEEF-vdW', 'color': 'yellow'},
}

# CE39 dataset

## Experimental data

In [6]:
raw_data = { # Taken from Surf. Sci. 640, 36–44 (2015).
    "#": list(range(1, 40)),
    "Surface reaction": [
        "CO + Ni(111) → CO/Ni(111)",
        "CO + Pt(111) → CO/Pt(111)",
        "CO + Pd(111) → CO/Pd(111)",
        "CO + Pd(100) → CO/Pd(100)",
        "CO + Rh(111) → CO/Rh(111)",
        "CO + Ir(111) → CO/Ir(111)",
        "CO + Cu(111) → CO/Cu(111)",
        "CO + Ru(001) → CO/Ru(001)",
        "CO + Co(001) → CO/Co(001)",
        "NO + Ni(100) → N/Ni(100) + O/Ni(100)",
        "NO + Pt(111) → NO/Pt(111)",
        "NO + Pd(111) → NO/Pd(111)",
        "NO + Pd(100) → NO/Pd(100)",
        "O2 + Ni(111) → 2O/Ni(111)",
        "O2 + Ni(100) → 2O/Ni(100)",
        "O2 + Pt(111) → 2O/Pt(111)",
        "O2 + Rh(100) → 2O/Rh(100)",
        "H2 + Pt(111) → 2H/Pt(111)",
        "H2 + Ni(111) → 2H/Ni(111)",
        "H2 + Ni(100) → 2H/Ni(100)",
        "H2 + Rh(111) → 2H/Rh(111)",
        "H2 + Pd(111) → 2H/Pd(111)",
        "I2 + Pt(111) → 2I/Pt(111)",
        "CH2I2 + Pt(111) → CH/Pt(111) + H/Pt(111) + 2I/Pt(111)",
        "CH3I + Pt(111) → CH3/Pt(111) + I/Pt(111)",
        "NH3 + Cu(100) → NH3/Cu(100)",
        "CH3I + Pt(111) → CH3I/Pt(111)",
        "CH3OH + Pt(111) → CH3OH/Pt(111)",
        "CH4 + Pt(111) → CH4/Pt(111)",
        "C2H6 + Pt(111) → C2H6/Pt(111)",
        "C3H8 + Pt(111) → C3H8/Pt(111)",
        "C4H10 + Pt(111) → C4H10/Pt(111)",
        "C6H6 + Pt(111) → C6H6/Pt(111)",
        "C6H6 + Cu(111) → C6H6/Cu(111)",
        "C6H6 + Ag(111) → C6H6/Ag(111)",
        "C6H6 + Au(111) → C6H6/Au(111)",
        "C6H10 + Pt(111) → C6H10/Pt(111)",
        "H2O + Pt(111) → H2O/Pt(111)",
        "H2O + OPt(111) → H2OOH/Pt(111)"
    ],
    "Coverage (ML)": [
        "1/4", "1/4", "1/4", "1/4", "1/4", "1/4", "1/4", "1/4", "1/4", "1/8", "1/4", "1/4", "1/4", "1/8",
        "1/8", "1/18", "1/8", "1/8", "1/8", "1/8", "1/8", "1/8", "1/4", "1/4", "1/4", "1/4", "1/4",
        "1/4", "1/4", "1/9", "1/9", "1/9", "1/9", "1/9", "1/9", "1/9", "1/9", "1/4", "1/2"
    ],
    "Reaction enthalpy (kJ/mol)": [
        -122, -120, -143, -155, -139, -158, -53, -158, -115, -290, -114, -179, -161, -480,
        -530, -208, -358, -72, -94, -94, -70, -88, -312, -473, -212, -57, -84.5, -56, -15,
        -28.5, -41.3, -50.8, -164, -68, -63, -72, -122, -51.3, -57.4
    ],
    "Temp. (K)": [
        350, 340, 450, 430, 500, 420, 350, 475, 370, 300, 300, 520, 300, 300,
        300, 515, 300, 300, 370, 370, 325, 370, 0, 210, 320, 235, 100, 100,
        63, 106, 139, 171, 300, 225, 210, 230, 100, 120, 150
    ],
    "Reaction energy (kJ/mol)": [
        -119, -117, -139, -151, -135, -154, -52, -154, -112, -288, -112, -175, -159, -479,
        -528, -204, -356, -70, -91, -91, -67, -85, -230, -471, -209, -55, -83.7, -55,
        -14.5, -27.6, -40.1, -49.4, -300, -66, -61, -70, -121, -50.3, -56.2
    ],
    "Reaction energy without ZPE (kJ/mol)": [
        -124, -124, -144, -157, -142, -164, -57, -161, -119, -299,
        -119, -182, -163, -485, -530, -208, -355, -72, -100, -87,
        -72, -90, -313, -455, -209
    ] + [
        -60, -84, -55, -14, -27, -39, -48, -162, -66, -61,
        -70, -123, -55, -66
    ],
    "Weight": [ 1, 1, 1, 1, 1, 1, 1, 1, 1,0.5, 1, 1, 1, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,0.5, 0.5, 0.5, 0.5, 0.25, 0.5] + [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,1]
}

ce39_dataset_dict = {}

calc_molecule_list = []
calc_molecule_surface_list = []

for ce39_idx in range(39):


    if 'Co' in raw_data['Surface reaction'][ce39_idx] or 'Ru' in raw_data['Surface reaction'][ce39_idx]:
        crystal_type = 'hcp'
    else:
        crystal_type = 'fcc'

    # Set the supercell_size based on coverage
    if raw_data['Coverage (ML)'][ce39_idx] in ['1/4','1/8']:
        surface_sc_size = '2x2'
    else:
        surface_sc_size = '3x3'

    surface_type = raw_data['Surface reaction'][ce39_idx].split()[2].replace('(',f'_{crystal_type}_').replace(')',f'_{surface_sc_size}')
    system_molecule = raw_data['Surface reaction'][ce39_idx].split()[0]
    molecule_surface_system_list = []
    for molecule_surface_system in raw_data['Surface reaction'][ce39_idx].split('→')[1].split('+'):
        if molecule_surface_system.strip()[0].isdigit():
            molecule_surface_system_list += [molecule_surface_system.strip()[1:].replace('/','-').replace('(',f'_{crystal_type}_').replace(')',f'_{surface_sc_size}')]*int(molecule_surface_system.strip()[0])
        else:
            molecule_surface_system_list += [molecule_surface_system.strip().replace('/','-').replace('(',f'_{crystal_type}_').replace(')',f'_{surface_sc_size}')]


    ce39_dataset_dict[f'{ce39_idx+1:02d}'] = {'Reaction': raw_data['Surface reaction'][ce39_idx], 'MAD Weight': raw_data['Weight'][ce39_idx], 'Reactant Molecule': [system_molecule], 'Reactant Surface': [surface_type], 'Products': molecule_surface_system_list, 'Reaction Enthalpy': int(raw_data["Reaction enthalpy (kJ/mol)"][ce39_idx]), 'Reaction Energy': int(raw_data["Reaction energy (kJ/mol)"][ce39_idx]),'Reaction Energy without ZPE': int(raw_data["Reaction energy without ZPE (kJ/mol)"][ce39_idx])}

    for molecule_surface_system in molecule_surface_system_list:
        if molecule_surface_system not in calc_molecule_surface_list:
            calc_molecule_surface_list += [molecule_surface_system]
    
    if system_molecule not in calc_molecule_list:
        calc_molecule_list += [system_molecule]

ce39_dataset_df = pd.DataFrame.from_dict(ce39_dataset_dict, orient='index')
display(ce39_dataset_df)

,Reaction,MAD Weight,Reactant Molecule,Reactant Surface,Products,Reaction Enthalpy,Reaction Energy,Reaction Energy without ZPE
01,CO + Ni(111) → CO/Ni(111),1.00,[CO],[Ni_fcc_111_2x2],[CO-Ni_fcc_111_2x2],-122,-119,-124
02,CO + Pt(111) → CO/Pt(111),1.00,[CO],[Pt_fcc_111_2x2],[CO-Pt_fcc_111_2x2],-120,-117,-124
03,CO + Pd(111) → CO/Pd(111),1.00,[CO],[Pd_fcc_111_2x2],[CO-Pd_fcc_111_2x2],-143,-139,-144
04,CO + Pd(100) → CO/Pd(100),1.00,[CO],[Pd_fcc_100_2x2],[CO-Pd_fcc_100_2x2],-155,-151,-157
05,CO + Rh(111) → CO/Rh(111),1.00,[CO],[Rh_fcc_111_2x2],[CO-Rh_fcc_111_2x2],-139,-135,-142
06,CO + Ir(111) → CO/Ir(111),1.00,[CO],[Ir_fcc_111_2x2],[CO-Ir_fcc_111_2x2],-158,-154,-164
07,CO + Cu(111) → CO/Cu(111),1.00,[CO],[Cu_fcc_111_2x2],[CO-Cu_fcc_111_2x2],-53,-52,-57
08,CO + Ru(001) → CO/Ru(001),1.00,[CO],[Ru_hcp_001_2x2],[CO-Ru_hcp_001_2x2],-158,-154,-161
09,CO + Co(001) → CO/Co(001),1.00,[CO],[Co_hcp_001_2x2],[CO-Co_hcp_001_2x2],-115,-112,-119
10,NO + Ni(100) → N/Ni(100) + O/Ni(100),0.50,[NO],[Ni_fcc_100_2x2],"[N-Ni_fcc_100_2x2, O-Ni_fcc_100_2x2]",-290,-288,-299
11,NO + Pt(111) → NO/Pt(111),1.00,[NO],[Pt_fcc_111_2x2],[NO-Pt_fcc_111_2x2],-114,-112,-119
12,NO + Pd(111) → NO/Pd(111),1.00,[NO],[Pd_fcc_111_2x2],[NO-Pd_fcc_111_2x2],-179,-175,-182
13,NO + Pd(100) → NO/Pd(100),1.00,[NO],[Pd_fcc_100_2x2],[NO-Pd_fcc_100_2x2],-161,-159,-163
14,O2 + Ni(111) → 2O/Ni(111),0.50,[O2],[Ni_fcc_111_2x2],"[O-Ni_fcc_111_2x2, O-Ni_fcc_111_2x2]",-480,-479,-485
15,O2 + Ni(100) → 2O/Ni(100),0.50,[O2],[Ni_fcc_100_2x2],"[O-Ni_fcc_100_2x2, O-Ni_fcc_100_2x2]",-530,-528,-530
16,O2 + Pt(111) → 2O/Pt(111),0.50,[O2],[Pt_fcc_111_3x3],"[O-Pt_fcc_111_3x3, O-Pt_fcc_111_3x3]",-208,-204,-208
17,O2 + Rh(100) → 2O/Rh(100),0.50,[O2],[Rh_fcc_100_2x2],"[O-Rh_fcc_100_2x2, O-Rh_fcc_100_2x2]",-358,-356,-355
18,H2 + Pt(111) → 2H/Pt(111),0.50,[H2],[Pt_fcc_111_2x2],"[H-Pt_fcc_111_2x2, H-Pt_fcc_111_2x2]",-72,-70,-72
19,H2 + Ni(111) → 2H/Ni(111),0.50,[H2],[Ni_fcc_111_2x2],"[H-Ni_fcc_111_2x2, H-Ni_fcc_111_2x2]",-94,-91,-100
20,H2 + Ni(100) → 2H/Ni(100),0.50,[H2],[Ni_fcc_100_2x2],"[H-Ni_fcc_100_2x2, H-Ni_fcc_100_2x2]",-94,-91,-87
21,H2 + Rh(111) → 2H/Rh(111),0.50,[H2],[Rh_fcc_111_2x2],"[H-Rh_fcc_111_2x2, H-Rh_fcc_111_2x2]",-70,-67,-72
22,H2 + Pd(111) → 2H/Pd(111),0.50,[H2],[Pd_fcc_111_2x2],"[H-Pd_fcc_111_2x2, H-Pd_fcc_111_2x2]",-88,-85,-90
23,I2 + Pt(111) → 2I/Pt(111),0.50,[I2],[Pt_fcc_111_2x2],"[I-Pt_fcc_111_2x2, I-Pt_fcc_111_2x2]",-312,-230,-313
24,CH2I2 + Pt(111) → CH/Pt(111) + H/Pt(111) + 2I/...,0.25,[CH2I2],[Pt_fcc_111_2x2],"[CH-Pt_fcc_111_2x2, H-Pt_fcc_111_2x2, I-Pt_fcc...",-473,-471,-455
25,CH3I + Pt(111) → CH3/Pt(111) + I/Pt(111),0.50,[CH3I],[Pt_fcc_111_2x2],"[CH3-Pt_fcc_111_2x2, I-Pt_fcc_111_2x2]",-212,-209,-209
26,NH3 + Cu(100) → NH3/Cu(100),1.00,[NH3],[Cu_fcc_100_2x2],[NH3-Cu_fcc_100_2x2],-57,-55,-60
27,CH3I + Pt(111) → CH3I/Pt(111),1.00,[CH3I],[Pt_fcc_111_2x2],[CH3I-Pt_fcc_111_2x2],-84,-83,-84
28,CH3OH + Pt(111) → CH3OH/Pt(111),1.00,[CH3OH],[Pt_fcc_111_2x2],[CH3OH-Pt_fcc_111_2x2],-56,-55,-55
29,CH4 + Pt(111) → CH4/Pt(111),1.00,[CH4],[Pt_fcc_111_2x2],[CH4-Pt_fcc_111_2x2],-15,-14,-14
30,C2H6 + Pt(111) → C2H6/Pt(111),1.00,[C2H6],[Pt_fcc_111_3x3],[C2H6-Pt_fcc_111_3x3],-28,-27,-27
31,C3H8 + Pt(111) → C3H8/Pt(111),1.00,[C3H8],[Pt_fcc_111_3x3],[C3H8-Pt_fcc_111_3x3],-41,-40,-39
32,C4H10 + Pt(111) → C4H10/Pt(111),1.00,[C4H10],[Pt_fcc_111_3x3],[C4H10-Pt_fcc_111_3x3],-50,-49,-48
33,C6H6 + Pt(111) → C6H6/Pt(111),1.00,[C6H6],[Pt_fcc_111_3x3],[C6H6-Pt_fcc_111_3x3],-164,-300,-162
34,C6H6 + Cu(111) → C6H6/Cu(111),1.00,[C6H6],[Cu_fcc_111_3x3],[C6H6-Cu_fcc_111_3x3],-68,-66,-66
35,C6H6 + Ag(111) → C6H6/Ag(111),1.00,[C6H6],[Ag_fcc_111_3x3],[C6H6-Ag_fcc_111_3x3],-63,-61,-61
36,C6H6 + Au(111) → C6H6/Au(111),1.00,[C6H6],[Au_fcc_111_3x3],[C6H6-Au_fcc_111_3x3],-72,-70,-70
37,C6H10 + Pt(111) → C6H10/Pt(111),1.00,[C6H10],[Pt_fcc_111_3x3],[C6H10-Pt_fcc_111_3x3],-122,-121,-123
38,H2O + Pt(111) → H2O/Pt(111),1.00,[H2O],[Pt_fcc_111_2x2],[H2O-Pt_fcc_111_2x2],-51,-50,-55
39,H2O + OPt(111) → H2OOH/Pt(111),1.00,[H2O],[OPt_fcc_111_3x3],[H2OOH-Pt_fcc_111_3x3],-57,-56,-66

## DFT estimates

### BEEF-vdW

In [12]:
# Calculate the adsorption energy from BEEF-vdW with a 4L and 6L slab
vasp_method = 'vasp'

ce39_eads_dict = {ce39_idx: {'Reaction': '', 'Experiment': 0, 'BEEFvdW (4L)': 0, 'BEEFvdW (6L)': 0} for ce39_idx in ce39_dataset_dict}

for method in ['4L','6L']:
    if method == '4L':
        root_folder = f'Data/CE39/Eads_BEEFvdW_4L'
    elif method == '6L':
        root_folder = f'Data/CE39/Eads_BEEFvdW_6L'

    for ce39_idx in ce39_dataset_dict:
        reactant_molecule = ce39_dataset_dict[ce39_idx]['Reactant Molecule'][0]
        reactant_surface = ce39_dataset_dict[ce39_idx]['Reactant Surface'][0]
        products = ce39_dataset_dict[ce39_idx]['Products']
        sc_size = products[0].split('_')[-1]  # Extract the supercell size from the first product
        num_products = len(products)

        total_product_energy = 0
        for product_idx in range(num_products):
            total_product_energy += get_energy(f'{root_folder}/Molecule-Surface/{method}_{products[product_idx]}/OUTCAR.gz', code='vasp')

        if 'H2OOH' not in ce39_dataset_dict[ce39_idx]['Reaction']:
            reactant_molecule_energy = get_energy(f'{root_folder}/Molecule/{reactant_molecule}/OUTCAR.gz', code='vasp')
            reactant_surface_energy = get_energy(f'{root_folder}/Surface/{method}_{reactant_surface}/OUTCAR.gz', code='vasp')
            ce39_eads_dict[ce39_idx][f'BEEFvdW ({method})'] = (total_product_energy - reactant_molecule_energy - num_products * reactant_surface_energy) * 1000 / kjmol_to_meV
        else:
            reactant_molecule_energy = get_energy(f'{root_folder}/Molecule/{reactant_molecule}/OUTCAR.gz', code='vasp')
            reactant_surface_energy = (1/3)*get_energy(f'{root_folder}/Molecule-Surface/{method}_O-Pt_fcc_111_{sc_size}/OUTCAR.gz', code='vasp')  - (1/9)*get_energy(f'{root_folder}/Surface/{method}_Pt_fcc_111_{sc_size}/OUTCAR.gz', code='vasp') 
            ce39_eads_dict[ce39_idx][f'BEEFvdW ({method})'] = (2 / 9 * total_product_energy - reactant_molecule_energy - reactant_surface_energy) * 1000 / kjmol_to_meV

        ce39_eads_dict[ce39_idx]['Experiment'] = ce39_dataset_dict[ce39_idx]['Reaction Energy without ZPE']
        ce39_eads_dict[ce39_idx]['Reaction'] = ce39_dataset_dict[ce39_idx]['Reaction']

# Convert to DataFrame
ce39_eads_df = pd.DataFrame.from_dict(ce39_eads_dict, orient='index')
mad_dict = {method: np.mean(abs(ce39_eads_df[method] - ce39_eads_df['Experiment']) * ce39_dataset_df['MAD Weight']) for method in ['BEEFvdW (4L)', 'BEEFvdW (6L)']}
# Add an additional row at the bottom that is the MAD for each method
ce39_eads_df.loc['MAD'] = ['MAD', 0, mad_dict['BEEFvdW (4L)'], mad_dict['BEEFvdW (6L)']]

# Round to nearest integer and convert to integer
ce39_eads_df = ce39_eads_df.round(0).astype({'Experiment': 'Int64', 'BEEFvdW (4L)': 'Int64', 'BEEFvdW (6L)': 'Int64', 'Reaction': str}) 

display(ce39_eads_df)

,Reaction,Experiment,BEEFvdW (4L),BEEFvdW (6L)
01,CO + Ni(111) → CO/Ni(111),-124,-150,-151
02,CO + Pt(111) → CO/Pt(111),-124,-133,-135
03,CO + Pd(111) → CO/Pd(111),-144,-158,-148
04,CO + Pd(100) → CO/Pd(100),-157,-152,-150
05,CO + Rh(111) → CO/Rh(111),-142,-161,-163
06,CO + Ir(111) → CO/Ir(111),-164,-172,-179
07,CO + Cu(111) → CO/Cu(111),-57,-52,-50
08,CO + Ru(001) → CO/Ru(001),-161,-162,-156
09,CO + Co(001) → CO/Co(001),-119,-135,-137
10,NO + Ni(100) → N/Ni(100) + O/Ni(100),-299,-393,-385
11,NO + Pt(111) → NO/Pt(111),-119,-150,-156
12,NO + Pd(111) → NO/Pd(111),-182,-189,-190
13,NO + Pd(100) → NO/Pd(100),-163,-172,-173
14,O2 + Ni(111) → 2O/Ni(111),-485,-433,-430
15,O2 + Ni(100) → 2O/Ni(100),-530,-482,-476
16,O2 + Pt(111) → 2O/Pt(111),-208,-192,-208
17,O2 + Rh(100) → 2O/Rh(100),-355,-395,-366
18,H2 + Pt(111) → 2H/Pt(111),-72,-41,-48
19,H2 + Ni(111) → 2H/Ni(111),-100,-67,-66
20,H2 + Ni(100) → 2H/Ni(100),-87,-55,-53
21,H2 + Rh(111) → 2H/Rh(111),-72,-58,-58
22,H2 + Pd(111) → 2H/Pd(111),-90,-63,-39
23,I2 + Pt(111) → 2I/Pt(111),-313,-269,-282
24,CH2I2 + Pt(111) → CH/Pt(111) + H/Pt(111) + 2I/...,-455,-334,-356
25,CH3I + Pt(111) → CH3/Pt(111) + I/Pt(111),-209,-161,-172
26,NH3 + Cu(100) → NH3/Cu(100),-60,-37,-35
27,CH3I + Pt(111) → CH3I/Pt(111),-84,-62,-63
28,CH3OH + Pt(111) → CH3OH/Pt(111),-55,-33,-33
29,CH4 + Pt(111) → CH4/Pt(111),-14,-16,-16
30,C2H6 + Pt(111) → C2H6/Pt(111),-27,-15,-22
31,C3H8 + Pt(111) → C3H8/Pt(111),-39,-30,-30
32,C4H10 + Pt(111) → C4H10/Pt(111),-48,-40,-40
33,C6H6 + Pt(111) → C6H6/Pt(111),-162,-74,-89
34,C6H6 + Cu(111) → C6H6/Cu(111),-66,-40,-40
35,C6H6 + Ag(111) → C6H6/Ag(111),-61,-35,-36
36,C6H6 + Au(111) → C6H6/Au(111),-70,-41,-42
37,C6H10 + Pt(111) → C6H10/Pt(111),-123,-77,-88
38,H2O + Pt(111) → H2O/Pt(111),-55,-22,-22
39,H2O + OPt(111) → H2OOH/Pt(111),-66,-54,-55
MAD,MAD,0,20,19

## Comparison between NSC-DFAs, RPA and DFT

In [23]:
ce39_int_dict

{'01': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -43432.31148274403,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '02': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -48142.3756564037,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '03': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -53792.24498080611,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '04': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -57692.22473322632,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '05': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -61477.401212591656,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '06': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -68724.95517271628,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '07': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -78192.09141928871,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '08': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -80151.46435180579,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '09': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -90271.325805035,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '10': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -97894.05918344564,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '11': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -105446.94316872915,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '12': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -110863.33202038272,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '13': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -114520.73300621677,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '14': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -118303.0586836238,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '15': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -126242.5945483391,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '16': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -133580.74133251482,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '17': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -154063.90596362273,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '18': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -166120.42359173333,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '19': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -175521.48283065335,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '20': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -183083.83088374144,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '21': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -190334.35789756535,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '22': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -202910.9410943246,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '23': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -209023.00269918333,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '24': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -217866.04718382575,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '25': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -236621.13497354192,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '26': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -247080.44230326437,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '27': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -249451.17089661863,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '28': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -255573.972346596,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '29': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -262596.31243195845,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '30': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -269188.13589115295,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '31': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -282673.7502002433,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '32': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -297660.5995368327,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '33': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -314186.10344961245,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '34': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -330602.45112886844,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '35': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -338712.46974755527,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '36': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -342879.85884995636,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '37': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -349877.5973724048,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '38': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -367750.4404130737,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0},
 '39': {'Reaction': '',
  'Experiment': 0,
  'RPA': 0,
  'BEEFvdW': -83011.65461945561,
  'hBEEFvdW': 0,
  'dhBEEFvdW': 0}}

In [ ]:
# Analyse the interaction energy calculations
vasp_method = 'vasp'

ce39_int_dict = {ce39_idx: {'RPA': 0 , 'BEEFvdW': 0, 'hBEEFvdW': 0,'dhBEEFvdW': 0} for ce39_idx in ce39_dataset_dict}
final_ce39_eads_dict = {ce39_idx: {'Reaction': '', 'Experiment': 0, 'RPA': 0 , 'BEEFvdW': 0, 'hBEEFvdW': 0, 'dhBEEFvdW': 0} for ce39_idx in ce39_dataset_dict}

# Start by analyzing BEEFvdW
root_folder = "Data/CE39/Eint_BEEFvdW"
for ce39_idx in ce39_int_dict:
    reactant_molecule = ce39_dataset_dict[ce39_idx]['Reactant Molecule'][0]
    reactant_surface = ce39_dataset_dict[ce39_idx]['Reactant Surface'][0]
    products = ce39_dataset_dict[ce39_idx]['Products']
    sc_size = products[0].split('_')[-1]  # Extract the supercell size from the first product
    num_products = len(products)

    total_product_energy = 0
    for product_idx in range(num_products):
        total_product_energy += get_energy(f'{root_folder}/Molecule-Surface/4L_{products[product_idx]}/OUTCAR.gz', code='vasp')

    if 'H2OOH' not in ce39_dataset_dict[ce39_idx]['Reaction']:
        reactant_molecule_energy = get_energy(f'{root_folder}/Molecule/4L_{reactant_molecule}_{reactant_surface}/OUTCAR.gz', code='vasp')
        reactant_surface_energy = get_energy(f'{root_folder}/Surface/4L_{reactant_surface}/OUTCAR.gz', code='vasp')
        ce39_int_dict[ce39_idx]['BEEFvdW'] = (total_product_energy - reactant_molecule_energy - num_products * reactant_surface_energy) * 1000 / kjmol_to_meV
    else:
        reactant_molecule_energy = get_energy(f'{root_folder}/Molecule/4L_{reactant_molecule}_Pt_fcc_111_{sc_size}/OUTCAR.gz', code='vasp')
        reactant_surface_energy = (1/3)*get_energy(f'{root_folder}/Molecule-Surface/4L_O-Pt_fcc_111_{sc_size}/OUTCAR.gz', code='vasp') - (1/9)*get_energy(f'{root_folder}/Surface/4L_Pt_fcc_111_{sc_size}/OUTCAR.gz', code='vasp') 
        ce39_int_dict[ce39_idx]['BEEFvdW'] = (2 / 9 * total_product_energy - reactant_molecule_energy - reactant_surface_energy) * 1000 / kjmol_to_meV


# Analyze hBEEFvdW, dhBEEFvdW and RPA
root_folder = f'Data/CE39/Eint_hBEEFvdW'
rpa_root_folder = f'Data/CE39/Eint_RPA'

for ce39_idx in ce39_int_dict:
    reactant_molecule = ce39_dataset_dict[ce39_idx]['Reactant Molecule'][0]
    reactant_surface = ce39_dataset_dict[ce39_idx]['Reactant Surface'][0]
    products = ce39_dataset_dict[ce39_idx]['Products']
    sc_size = products[0].split('_')[-1]  # Extract the supercell size from the first product
    num_products = len(products)
    calc_energy_dict = {
        '00': {'total_product_energy': 0, 'reactant_molecule_energy': 0, 'reactant_surface_energy': 0, 'eint': 0},
        '01': {'total_product_energy': 0, 'reactant_molecule_energy': 0, 'reactant_surface_energy': 0, 'eint': 0},
        '02': {'total_product_energy': 0, 'reactant_molecule_energy': 0, 'reactant_surface_energy': 0, 'eint': 0},
        '03_3': {'total_product_energy': 0, 'reactant_molecule_energy': 0, 'reactant_surface_energy': 0, 'eint': 0}
    }
    # hBEEF part
    for calc_type in calc_energy_dict:
        for product_idx in range(num_products):
            calc_energy_dict[calc_type]['total_product_energy'] += get_energy(f'{root_folder}/Molecule-Surface/4L_{products[product_idx]}/OUTCAR_{calc_type}.gz', code='vasp')

        if 'H2OOH' not in ce39_dataset_dict[ce39_idx]['Reaction']:
            calc_energy_dict[calc_type]['reactant_molecule_energy'] = get_energy(f'{root_folder}/Molecule/4L_{reactant_molecule}_{reactant_surface}/OUTCAR_{calc_type}.gz', code='vasp')
            calc_energy_dict[calc_type]['reactant_surface_energy'] = get_energy(f'{root_folder}/Surface/4L_{reactant_surface}/OUTCAR_{calc_type}.gz', code='vasp')
            calc_energy_dict[calc_type]['eint'] = (calc_energy_dict[calc_type]['total_product_energy'] - calc_energy_dict[calc_type]['reactant_molecule_energy'] - num_products * calc_energy_dict[calc_type]['reactant_surface_energy']) * 1000 / kjmol_to_meV
        else:
            calc_energy_dict[calc_type]['reactant_molecule_energy'] = get_energy(f'{root_folder}/Molecule/4L_{reactant_molecule}_Pt_fcc_111_{sc_size}/OUTCAR_{calc_type}.gz', code='vasp')
            calc_energy_dict[calc_type]['reactant_surface_energy'] = (1/3)*get_energy(f'{root_folder}/Molecule-Surface/4L_O-Pt_fcc_111_{sc_size}/OUTCAR_{calc_type}.gz', code='vasp') - (1/9)*get_energy(f'{root_folder}/Surface/4L_Pt_fcc_111_{sc_size}/OUTCAR_{calc_type}.gz', code='vasp') 
            calc_energy_dict[calc_type]['eint'] = (2 / 9 * calc_energy_dict[calc_type]['total_product_energy'] - calc_energy_dict[calc_type]['reactant_molecule_energy'] - calc_energy_dict[calc_type]['reactant_surface_energy']) * 1000 / kjmol_to_meV

    # RPA correlation part
    total_product_energy = 0
    for product_idx in range(num_products):
        total_product_energy += get_energy(f'{rpa_root_folder}/Molecule-Surface/4L_{products[product_idx]}/OUTCAR_04_RPA.gz', code='vasp_rpa')

    if 'H2OOH' not in ce39_dataset_dict[ce39_idx]['Reaction']:
        reactant_molecule_energy = get_energy(f'{rpa_root_folder}/Molecule/4L_{reactant_molecule}_{reactant_surface}/OUTCAR_04_RPA.gz', code='vasp_rpa')
        reactant_surface_energy = get_energy(f'{rpa_root_folder}/Surface/4L_{reactant_surface}/OUTCAR_04_RPA.gz', code='vasp_rpa')
        rpac_eint = (total_product_energy - reactant_molecule_energy - num_products * reactant_surface_energy) * 1000 / kjmol_to_meV
    else:
        reactant_molecule_energy = get_energy(f'{rpa_root_folder}/Molecule/4L_{reactant_molecule}_Pt_fcc_111_{sc_size}/OUTCAR_04_RPA.gz', code='vasp_rpa')
        reactant_surface_energy = (1/3)*get_energy(f'{rpa_root_folder}/Molecule-Surface/4L_O-Pt_fcc_111_{sc_size}/OUTCAR_04_RPA.gz', code='vasp_rpa')- (1/9)*get_energy(f'{rpa_root_folder}/Surface/4L_Pt_fcc_111_{sc_size}/OUTCAR_04_RPA.gz', code='vasp_rpa') 
        rpac_eint = (2 / 9 * total_product_energy - reactant_molecule_energy - reactant_surface_energy) * 1000 / kjmol_to_meV

    # RPA EXX part
    total_product_energy = 0
    for product_idx in range(num_products):
        total_product_energy += get_energy(f'{rpa_root_folder}/Molecule-Surface/4L_{products[product_idx]}/OUTCAR_02_EXX.gz', code='vasp')

    if 'H2OOH' not in ce39_dataset_dict[ce39_idx]['Reaction']:
        reactant_molecule_energy = get_energy(f'{rpa_root_folder}/Molecule/4L_{reactant_molecule}_{reactant_surface}/OUTCAR_02_EXX.gz', code='vasp')
        reactant_surface_energy = get_energy(f'{rpa_root_folder}/Surface/4L_{reactant_surface}/OUTCAR_02_EXX.gz', code='vasp')
        rpax_eint = (total_product_energy - reactant_molecule_energy - num_products * reactant_surface_energy) * 1000 / kjmol_to_meV
    else:
        reactant_molecule_energy = get_energy(f'{rpa_root_folder}/Molecule/4L_{reactant_molecule}_Pt_fcc_111_{sc_size}/OUTCAR_02_EXX.gz', code='vasp')
        reactant_surface_energy = (1/3)*get_energy(f'{rpa_root_folder}/Molecule-Surface/4L_O-Pt_fcc_111_{sc_size}/OUTCAR_02_EXX.gz', code='vasp') - (1/9)*get_energy(f'{rpa_root_folder}/Surface/4L_Pt_fcc_111_{sc_size}/OUTCAR_02_EXX.gz', code='vasp') 
        rpax_eint = (2 / 9 * total_product_energy - reactant_molecule_energy - reactant_surface_energy) * 1000 / kjmol_to_meV


    beefx_eint = calc_energy_dict['02']['eint']
    exx_eint = calc_energy_dict['03_3']['eint']
    nlc_eint = calc_energy_dict['00']['eint'] - calc_energy_dict['01']['eint']
    beefc_eint = calc_energy_dict['01']['eint'] - calc_energy_dict['02']['eint']
    dh_x_frac = 0.25
    dh_c_frac = 0.15
    ce39_int_dict[ce39_idx]['dhBEEFvdW'] = dh_x_frac * exx_eint + (1-dh_x_frac)*beefx_eint + dh_c_frac*rpac_eint + (1-dh_c_frac)*beefc_eint + nlc_eint
    h_x_frac = 0.175
    ce39_int_dict[ce39_idx]['hBEEFvdW'] = h_x_frac * exx_eint + (1-h_x_frac)*beefx_eint + beefc_eint + nlc_eint
    ce39_int_dict[ce39_idx]['RPA'] = rpax_eint + rpac_eint

    final_ce39_eads_dict[ce39_idx]['Experiment'] = ce39_dataset_dict[ce39_idx]['Reaction Energy without ZPE']
    final_ce39_eads_dict[ce39_idx]['Reaction'] = ce39_dataset_dict[ce39_idx]['Reaction']


# Convert interaction energy to adsorption energy

for method in ['RPA','BEEFvdW','hBEEFvdW','dhBEEFvdW']:
    for ce39_idx in ce39_int_dict:
        final_ce39_eads_dict[ce39_idx][method] = ce39_int_dict[ce39_idx][method] - ce39_int_dict[ce39_idx]['BEEFvdW'] + ce39_eads_dict[ce39_idx]['BEEFvdW (6L)']

# Calculate the adsorption energy using BEEF-vdW
vasp_method = 'vasp'

ce39_dft_xc_eads_dict = {ce39_idx: {'Reaction': '', 'Experiment': 0} | {dft_xc : 0 for dft_xc in dft_xc_list} for ce39_idx in ce39_dataset_dict}

for dft_xc in dft_xc_list:
    root_folder = f'Data/CE39/DFT_XC'
    for ce39_idx in ce39_dft_xc_eads_dict:
        try:
            reactant_molecule = ce39_dataset_dict[ce39_idx]['Reactant Molecule'][0]
            reactant_surface = ce39_dataset_dict[ce39_idx]['Reactant Surface'][0]
            products = ce39_dataset_dict[ce39_idx]['Products']
            sc_size = products[0].split('_')[-1]  # Extract the supercell size from the first product
            num_products = len(products)

            total_product_energy = 0
            for product_idx in range(num_products):
                total_product_energy += get_energy(f'{root_folder}/Molecule-Surface/4L_{products[product_idx]}/OUTCAR_{dft_xc}', code='vasp')

            if 'H2OOH' not in ce39_dataset_dict[ce39_idx]['Reaction']:
                reactant_molecule_energy = get_energy(f'{root_folder}/Molecule/{reactant_molecule}/OUTCAR_{dft_xc}', code='vasp')
                reactant_surface_energy = get_energy(f'{root_folder}/Surface/4L_{reactant_surface}/OUTCAR_{dft_xc}', code='vasp')
                ce39_dft_xc_eads_dict[ce39_idx][dft_xc] = (total_product_energy - reactant_molecule_energy - num_products * reactant_surface_energy) * 1000 / kJmol2meV + ce39_eads_dict[ce39_idx]['BEEFvdW (6L)'] - ce39_eads_dict[ce39_idx]['BEEFvdW (4L)']
            else:
                reactant_molecule_energy = get_energy(f'{root_folder}/Molecule/{reactant_molecule}/OUTCAR_{dft_xc}', code='vasp')
                reactant_surface_energy = (1/3)*get_energy(f'{root_folder}/Molecule-Surface/4L_O-Pt_fcc_111_{sc_size}/OUTCAR_{dft_xc}', code='vasp')  - (1/9)*get_energy(f'{root_folder}/Surface/4L_Pt_fcc_111_{sc_size}/OUTCAR_{dft_xc}', code='vasp') 
                ce39_dft_xc_eads_dict[ce39_idx][dft_xc] = (2 / 9 * total_product_energy - reactant_molecule_energy - reactant_surface_energy) * 1000 / kJmol2meV + ce39_eads_dict[ce39_idx]['BEEFvdW (6L)'] - ce39_eads_dict[ce39_idx]['BEEFvdW (4L)']

            ce39_dft_xc_eads_dict[ce39_idx]['Experiment'] = ce39_dataset_dict[ce39_idx]['Reaction Energy without ZPE']
            ce39_dft_xc_eads_dict[ce39_idx]['Reaction'] = ce39_dataset_dict[ce39_idx]['Reaction']
        # print(ce39_int_dict[ce39_idx]['Reaction'], total_product_energy, reactant_molecule_energy, reactant_surface_energy, ce39_int_dict[ce39_idx]['RPA'])
        except:
            print(f"Error processing reaction {ce39_idx}: {ce39_dataset_dict[ce39_idx]['Reaction']}")
            continue

In [31]:
ce39_int_dict

{'01': {'RPA': -98.23393659927467,
  'BEEFvdW': -149.23116278004022,
  'hBEEFvdW': -137.52097467897727,
  'dhBEEFvdW': -138.3818920094924},
 '02': {'RPA': -133.06607768723273,
  'BEEFvdW': -133.40581215425186,
  'hBEEFvdW': -153.47950461277594,
  'dhBEEFvdW': -145.21359273906023},
 '03': {'RPA': -148.96420559795638,
  'BEEFvdW': -161.19553413357534,
  'hBEEFvdW': -176.61411829891932,
  'dhBEEFvdW': -162.16334667431383},
 '04': {'RPA': -148.68814393443623,
  'BEEFvdW': -154.54307498023314,
  'hBEEFvdW': -166.87065084836283,
  'dhBEEFvdW': -157.77709925984018},
 '05': {'RPA': -138.20635678900157,
  'BEEFvdW': -160.64965485484646,
  'hBEEFvdW': -176.2965190965569,
  'dhBEEFvdW': -167.65728552109357},
 '06': {'RPA': -150.42955637743157,
  'BEEFvdW': -170.76060664402814,
  'hBEEFvdW': -187.2633132040079,
  'dhBEEFvdW': -179.258674067891},
 '07': {'RPA': -44.39197146343825,
  'BEEFvdW': -50.58621219957913,
  'hBEEFvdW': -44.69272944522881,
  'dhBEEFvdW': -52.3064989743943},
 '08': {'RPA': -148.1295366000504,
  'BEEFvdW': -162.9695578472063,
  'hBEEFvdW': -173.70670851641705,
  'dhBEEFvdW': -168.19084642957114},
 '09': {'RPA': -103.60503221760982,
  'BEEFvdW': -135.10771211670016,
  'hBEEFvdW': -118.12957407894008,
  'dhBEEFvdW': -132.0850237068532},
 '10': {'RPA': -419.40060492115185,
  'BEEFvdW': -397.4989236146585,
  'hBEEFvdW': -417.3989552582995,
  'dhBEEFvdW': -405.54602054500816},
 '11': {'RPA': -150.48213973568156,
  'BEEFvdW': -157.5411405724105,
  'hBEEFvdW': -193.1180638753019,
  'dhBEEFvdW': -159.0562966330287},
 '12': {'RPA': -179.8631081970737,
  'BEEFvdW': -199.06741185448357,
  'hBEEFvdW': -233.4025425585589,
  'dhBEEFvdW': -189.63224241875125},
 '13': {'RPA': -168.3152239455923,
  'BEEFvdW': -183.30981998341838,
  'hBEEFvdW': -207.65524092033206,
  'dhBEEFvdW': -175.48278622670054},
 '14': {'RPA': -461.0306204557491,
  'BEEFvdW': -429.222242622322,
  'hBEEFvdW': -436.12417852184115,
  'dhBEEFvdW': -443.68284892068255},
 '15': {'RPA': -513.9834201917879,
  'BEEFvdW': -479.5139217650375,
  'hBEEFvdW': -498.0430179175125,
  'dhBEEFvdW': -513.1537514275824},
 '16': {'RPA': -272.7230045710735,
  'BEEFvdW': -196.79049693733697,
  'hBEEFvdW': -213.0792302661094,
  'dhBEEFvdW': -209.76292049509843},
 '17': {'RPA': -443.0635503928122,
  'BEEFvdW': -394.381530751889,
  'hBEEFvdW': -399.5683749730385,
  'dhBEEFvdW': -398.86405790106414},
 '18': {'RPA': -87.49454310919631,
  'BEEFvdW': -43.36667497501865,
  'hBEEFvdW': -76.11430270733194,
  'dhBEEFvdW': -63.11924940288799},
 '19': {'RPA': -76.80325981120804,
  'BEEFvdW': -65.96061643051581,
  'hBEEFvdW': -66.31532700355659,
  'dhBEEFvdW': -66.08656918826478},
 '20': {'RPA': -43.997597448889394,
  'BEEFvdW': -53.04531361683491,
  'hBEEFvdW': -60.23390051752605,
  'dhBEEFvdW': -58.184193853986386},
 '21': {'RPA': -89.48714784137466,
  'BEEFvdW': -59.68066302609709,
  'hBEEFvdW': -82.30013790178242,
  'dhBEEFvdW': -77.0659143220179},
 '22': {'RPA': -105.5681220864511,
  'BEEFvdW': -65.59456940977171,
  'hBEEFvdW': -89.43622071657595,
  'dhBEEFvdW': -72.01298957826211},
 '23': {'RPA': -319.14251689000434,
  'BEEFvdW': -263.4587001347835,
  'hBEEFvdW': -317.4716093624533,
  'dhBEEFvdW': -324.57304558904264},
 '24': {'RPA': -429.6885237302416,
  'BEEFvdW': -321.7497254352143,
  'hBEEFvdW': -414.90038171548133,
  'dhBEEFvdW': -395.60554860221214},
 '25': {'RPA': -197.48166215147614,
  'BEEFvdW': -161.88189316242068,
  'hBEEFvdW': -199.91265644088142,
  'dhBEEFvdW': -200.70613012281598},
 '26': {'RPA': -4.046398619573523,
  'BEEFvdW': -42.333217679955126,
  'hBEEFvdW': -43.64006995279124,
  'dhBEEFvdW': -44.24851009606841},
 '27': {'RPA': -79.31017457377035,
  'BEEFvdW': -62.32229829066125,
  'hBEEFvdW': -79.72566190444633,
  'dhBEEFvdW': -85.60609901153428},
 '28': {'RPA': -21.73176034030482,
  'BEEFvdW': -27.13470331630394,
  'hBEEFvdW': -28.947537338476156,
  'dhBEEFvdW': -34.495851521204656},
 '29': {'RPA': -6.940172925984769,
  'BEEFvdW': -14.155367046604912,
  'hBEEFvdW': -15.058112308347052,
  'dhBEEFvdW': -16.199795051130437},
 '30': {'RPA': -26.883662026683865,
  'BEEFvdW': -21.260761157510775,
  'hBEEFvdW': -24.426847996862982,
  'dhBEEFvdW': -29.22775390743496},
 '31': {'RPA': -35.43601203659369,
  'BEEFvdW': -29.647474699976623,
  'hBEEFvdW': -32.6287988808324,
  'dhBEEFvdW': -39.17501448444245},
 '32': {'RPA': -39.8246216604672,
  'BEEFvdW': -37.80555177337691,
  'hBEEFvdW': -42.15643119859274,
  'dhBEEFvdW': -50.235468108660655},
 '33': {'RPA': -206.41981756436823,
  'BEEFvdW': -81.90894533188686,
  'hBEEFvdW': -153.95391141631956,
  'dhBEEFvdW': -156.09451718308912},
 '34': {'RPA': -40.24068495068371,
  'BEEFvdW': -35.86482456100561,
  'hBEEFvdW': -39.28918541385329,
  'dhBEEFvdW': -47.21342598989707},
 '35': {'RPA': -40.67864084013199,
  'BEEFvdW': -34.95689757858157,
  'hBEEFvdW': -37.62994181004363,
  'dhBEEFvdW': -45.5899649786128},
 '36': {'RPA': -40.03890045591206,
  'BEEFvdW': -41.44068782695315,
  'hBEEFvdW': -45.98162997060568,
  'dhBEEFvdW': -54.300786525583376},
 '37': {'RPA': -127.02604019604199,
  'BEEFvdW': -80.5487626486421,
  'hBEEFvdW': -110.00294222680145,
  'dhBEEFvdW': -116.12914975472098},
 '38': {'RPA': -11.520221896901688,
  'BEEFvdW': -19.187696592264604,
  'hBEEFvdW': -20.886447080475108,
  'dhBEEFvdW': -24.167054898508116},
 '39': {'RPA': -59.23053760885995,
  'BEEFvdW': -53.2173298124166,
  'hBEEFvdW': -58.34124156095531,
  'dhBEEFvdW': -65.87783188008893}}

In [32]:
final_ce39_eads_dict

{'01': {'Reaction': 'CO + Ni(111) → CO/Ni(111)',
  'Experiment': -124,
  'RPA': -99.7097675673653,
  'BEEFvdW': 0,
  'hBEEFvdW': -138.9968056470679,
  'dhBEEFvdW': -139.85772297758302},
 '02': {'Reaction': 'CO + Pt(111) → CO/Pt(111)',
  'Experiment': -124,
  'RPA': -134.99852259862985,
  'BEEFvdW': 0,
  'hBEEFvdW': -155.41194952417305,
  'dhBEEFvdW': -147.14603765045734},
 '03': {'Reaction': 'CO + Pd(111) → CO/Pd(111)',
  'Experiment': -144,
  'RPA': -135.86954523412936,
  'BEEFvdW': 0,
  'hBEEFvdW': -163.5194579350923,
  'dhBEEFvdW': -149.0686863104868},
 '04': {'Reaction': 'CO + Pd(100) → CO/Pd(100)',
  'Experiment': -157,
  'RPA': -143.71941462565323,
  'BEEFvdW': 0,
  'hBEEFvdW': -161.90192153957983,
  'dhBEEFvdW': -152.8083699510572},
 '05': {'Reaction': 'CO + Rh(111) → CO/Rh(111)',
  'Experiment': -142,
  'RPA': -140.36643858141514,
  'BEEFvdW': 0,
  'hBEEFvdW': -178.45660088897046,
  'dhBEEFvdW': -169.81736731350713},
 '06': {'Reaction': 'CO + Ir(111) → CO/Ir(111)',
  'Experiment': -164,
  'RPA': -159.1504767807932,
  'BEEFvdW': 0,
  'hBEEFvdW': -195.98423360736953,
  'dhBEEFvdW': -187.97959447125265},
 '07': {'Reaction': 'CO + Cu(111) → CO/Cu(111)',
  'Experiment': -57,
  'RPA': -43.949756991211146,
  'BEEFvdW': 0,
  'hBEEFvdW': -44.2505149730017,
  'dhBEEFvdW': -51.864284502167195},
 '08': {'Reaction': 'CO + Ru(001) → CO/Ru(001)',
  'Experiment': -161,
  'RPA': -141.642043244603,
  'BEEFvdW': 0,
  'hBEEFvdW': -167.21921516096967,
  'dhBEEFvdW': -161.70335307412375},
 '09': {'Reaction': 'CO + Co(001) → CO/Co(001)',
  'Experiment': -119,
  'RPA': -105.5402626605667,
  'BEEFvdW': 0,
  'hBEEFvdW': -120.06480452189696,
  'dhBEEFvdW': -134.02025414981009},
 '10': {'Reaction': 'NO + Ni(100) → N/Ni(100) + O/Ni(100)',
  'Experiment': -299,
  'RPA': -407.20428668678096,
  'BEEFvdW': 0,
  'hBEEFvdW': -405.2026370239286,
  'dhBEEFvdW': -393.34970231063727},
 '11': {'Reaction': 'NO + Pt(111) → NO/Pt(111)',
  'Experiment': -119,
  'RPA': -148.9462109482997,
  'BEEFvdW': 0,
  'hBEEFvdW': -191.58213508792005,
  'dhBEEFvdW': -157.52036784564683},
 '12': {'Reaction': 'NO + Pd(111) → NO/Pd(111)',
  'Experiment': -182,
  'RPA': -171.01489662375056,
  'BEEFvdW': 0,
  'hBEEFvdW': -224.55433098523577,
  'dhBEEFvdW': -180.7840308454281},
 '13': {'Reaction': 'NO + Pd(100) → NO/Pd(100)',
  'Experiment': -163,
  'RPA': -157.63130847988774,
  'BEEFvdW': 0,
  'hBEEFvdW': -196.9713254546275,
  'dhBEEFvdW': -164.79887076099598},
 '14': {'Reaction': 'O2 + Ni(111) → 2O/Ni(111)',
  'Experiment': -485,
  'RPA': -461.6031702101939,
  'BEEFvdW': 0,
  'hBEEFvdW': -436.69672827628597,
  'dhBEEFvdW': -444.25539867512737},
 '15': {'Reaction': 'O2 + Ni(100) → 2O/Ni(100)',
  'Experiment': -530,
  'RPA': -510.57440812921095,
  'BEEFvdW': 0,
  'hBEEFvdW': -494.63400585493554,
  'dhBEEFvdW': -509.74473936500544},
 '16': {'Reaction': 'O2 + Pt(111) → 2O/Pt(111)',
  'Experiment': -208,
  'RPA': -283.8076014326123,
  'BEEFvdW': 0,
  'hBEEFvdW': -224.1638271276482,
  'dhBEEFvdW': -220.84751735663724},
 '17': {'Reaction': 'O2 + Rh(100) → 2O/Rh(100)',
  'Experiment': -355,
  'RPA': -415.146728284483,
  'BEEFvdW': 0,
  'hBEEFvdW': -371.6515528647093,
  'dhBEEFvdW': -370.94723579273494},
 '18': {'Reaction': 'H2 + Pt(111) → 2H/Pt(111)',
  'Experiment': -72,
  'RPA': -92.4145203089819,
  'BEEFvdW': 0,
  'hBEEFvdW': -81.03427990711754,
  'dhBEEFvdW': -68.03922660267358},
 '19': {'Reaction': 'H2 + Ni(111) → 2H/Ni(111)',
  'Experiment': -100,
  'RPA': -76.34601099441008,
  'BEEFvdW': 0,
  'hBEEFvdW': -65.85807818675863,
  'dhBEEFvdW': -65.62932037146682},
 '20': {'Reaction': 'H2 + Ni(100) → 2H/Ni(100)',
  'Experiment': -87,
  'RPA': -44.099419385534816,
  'BEEFvdW': 0,
  'hBEEFvdW': -60.335722454171474,
  'dhBEEFvdW': -58.28601579063181},
 '21': {'Reaction': 'H2 + Rh(111) → 2H/Rh(111)',
  'Experiment': -72,
  'RPA': -88.11039669676485,
  'BEEFvdW': 0,
  'hBEEFvdW': -80.92338675717261,
  'dhBEEFvdW': -75.68916317740809},
 '22': {'Reaction': 'H2 + Pd(111) → 2H/Pd(111)',
  'Experiment': -90,
  'RPA': -79.38247166085849,
  'BEEFvdW': 0,
  'hBEEFvdW': -63.25057029098333,
  'dhBEEFvdW': -45.827339152669495},
 '23': {'Reaction': 'I2 + Pt(111) → 2I/Pt(111)',
  'Experiment': -313,
  'RPA': -337.81563983464866,
  'BEEFvdW': 0,
  'hBEEFvdW': -336.1447323070976,
  'dhBEEFvdW': -343.24616853368696},
 '24': {'Reaction': 'CH2I2 + Pt(111) → CH/Pt(111) + H/Pt(111) + 2I/Pt(111)',
  'Experiment': -455,
  'RPA': -464.0309988496232,
  'BEEFvdW': 0,
  'hBEEFvdW': -449.2428568348629,
  'dhBEEFvdW': -429.9480237215937},
 '25': {'Reaction': 'CH3I + Pt(111) → CH3/Pt(111) + I/Pt(111)',
  'Experiment': -209,
  'RPA': -207.9009704511679,
  'BEEFvdW': 0,
  'hBEEFvdW': -210.33196474057317,
  'dhBEEFvdW': -211.12543842250773},
 '26': {'Reaction': 'NH3 + Cu(100) → NH3/Cu(100)',
  'Experiment': -60,
  'RPA': 3.682886056257807,
  'BEEFvdW': 0,
  'hBEEFvdW': -35.910785276959906,
  'dhBEEFvdW': -36.51922542023708},
 '27': {'Reaction': 'CH3I + Pt(111) → CH3I/Pt(111)',
  'Experiment': -84,
  'RPA': -80.27606222536353,
  'BEEFvdW': 0,
  'hBEEFvdW': -80.6915495560395,
  'dhBEEFvdW': -86.57198666312746},
 '28': {'Reaction': 'CH3OH + Pt(111) → CH3OH/Pt(111)',
  'Experiment': -55,
  'RPA': -27.649290713081395,
  'BEEFvdW': 0,
  'hBEEFvdW': -34.865067711252735,
  'dhBEEFvdW': -40.41338189398123},
 '29': {'Reaction': 'CH4 + Pt(111) → CH4/Pt(111)',
  'Experiment': -14,
  'RPA': -8.437026118403946,
  'BEEFvdW': 0,
  'hBEEFvdW': -16.55496550076623,
  'dhBEEFvdW': -17.696648243549614},
 '30': {'Reaction': 'C2H6 + Pt(111) → C2H6/Pt(111)',
  'Experiment': -27,
  'RPA': -27.27515608912388,
  'BEEFvdW': 0,
  'hBEEFvdW': -24.818342059302996,
  'dhBEEFvdW': -29.619247969874973},
 '31': {'Reaction': 'C3H8 + Pt(111) → C3H8/Pt(111)',
  'Experiment': -39,
  'RPA': -35.8676874159088,
  'BEEFvdW': 0,
  'hBEEFvdW': -33.06047426014751,
  'dhBEEFvdW': -39.60668986375756},
 '32': {'Reaction': 'C4H10 + Pt(111) → C4H10/Pt(111)',
  'Experiment': -48,
  'RPA': -42.34056837644657,
  'BEEFvdW': 0,
  'hBEEFvdW': -44.67237791457211,
  'dhBEEFvdW': -52.75141482464002},
 '33': {'Reaction': 'C6H6 + Pt(111) → C6H6/Pt(111)',
  'Experiment': -162,
  'RPA': -213.40525628516912,
  'BEEFvdW': 0,
  'hBEEFvdW': -160.93935013712047,
  'dhBEEFvdW': -163.07995590389004},
 '34': {'Reaction': 'C6H6 + Cu(111) → C6H6/Cu(111)',
  'Experiment': -66,
  'RPA': -44.53442795680635,
  'BEEFvdW': 0,
  'hBEEFvdW': -43.58292841997593,
  'dhBEEFvdW': -51.50716899601971},
 '35': {'Reaction': 'C6H6 + Ag(111) → C6H6/Ag(111)',
  'Experiment': -61,
  'RPA': -41.652595630407205,
  'BEEFvdW': 0,
  'hBEEFvdW': -38.60389660031885,
  'dhBEEFvdW': -46.56391976888801},
 '36': {'Reaction': 'C6H6 + Au(111) → C6H6/Au(111)',
  'Experiment': -70,
  'RPA': -40.28358726010011,
  'BEEFvdW': 0,
  'hBEEFvdW': -46.22631677479374,
  'dhBEEFvdW': -54.54547332977143},
 '37': {'Reaction': 'C6H10 + Pt(111) → C6H10/Pt(111)',
  'Experiment': -123,
  'RPA': -134.79761535813145,
  'BEEFvdW': 0,
  'hBEEFvdW': -117.7745173888909,
  'dhBEEFvdW': -123.90072491681043},
 '38': {'Reaction': 'H2O + Pt(111) → H2O/Pt(111)',
  'Experiment': -55,
  'RPA': -14.604001199399697,
  'BEEFvdW': 0,
  'hBEEFvdW': -23.970226382973117,
  'dhBEEFvdW': -27.250834201006125},
 '39': {'Reaction': 'H2O + OPt(111) → H2OOH/Pt(111)',
  'Experiment': -66,
  'RPA': -60.61730843366927,
  'BEEFvdW': 0,
  'hBEEFvdW': -59.728012385764636,
  'dhBEEFvdW': -67.26460270489827}}

In [ ]:
# Conver to DataFrame
ce39_int_df = pd.DataFrame.from_dict(ce39_int_dict, orient='index')
# Round all values to nearest integer and convert to int astype
ce39_int_df = ce39_int_df.round(0).astype({'Experiment': 'Int64', 'RPA': 'Int64', 'RPA_beef': 'Int64', 'rSE': 'Int64',  'RPA+rSE': 'Int64', 'RPA+EXX75': 'Int64','BEEFvdW': 'Int64','hBEEFvdW': 'Int64', 'Reaction': str}) 


metrics_methods = ['RPA', 'BEEFvdW', 'hBEEFvdW', 'dhBEEFvdW']

# Convert final_ce39_eads_dict to DataFrame
final_ce39_eads_df = pd.DataFrame.from_dict(final_ce39_eads_dict, orient='index')

# Calculate the adsorption energy for several DFT XC functionals
vasp_method = 'vasp'

ce39_dft_xc_eads_dict = {ce39_idx: {'Reaction': '', 'Experiment': 0} | {dft_xc : 0 for dft_xc in dft_xc_list} for ce39_idx in ce39_dataset_dict}

for dft_xc in dft_xc_list:
    root_folder = f'Data/CE39/DFT_XC'
    for ce39_idx in ce39_dft_xc_eads_dict:
        try:
            reactant_molecule = ce39_dataset_dict[ce39_idx]['Reactant Molecule'][0]
            reactant_surface = ce39_dataset_dict[ce39_idx]['Reactant Surface'][0]
            products = ce39_dataset_dict[ce39_idx]['Products']
            sc_size = products[0].split('_')[-1]  # Extract the supercell size from the first product
            num_products = len(products)

            total_product_energy = 0
            for product_idx in range(num_products):
                total_product_energy += get_energy(f'{root_folder}/Molecule-Surface/4L_{products[product_idx]}/OUTCAR_{dft_xc}.gz', code='vasp')

            if 'H2OOH' not in ce39_dataset_dict[ce39_idx]['Reaction']:
                reactant_molecule_energy = get_energy(f'{root_folder}/Molecule/{reactant_molecule}/OUTCAR_{dft_xc}.gz', code='vasp')
                reactant_surface_energy = get_energy(f'{root_folder}/Surface/4L_{reactant_surface}/OUTCAR_{dft_xc}.gz', code='vasp')
                ce39_dft_xc_eads_dict[ce39_idx][dft_xc] = (total_product_energy - reactant_molecule_energy - num_products * reactant_surface_energy) * 1000 / kjmol_to_meV + ce39_eads_dict[ce39_idx]['BEEFvdW (6L)'] - ce39_eads_dict[ce39_idx]['BEEFvdW (4L)']
            else:
                reactant_molecule_energy = get_energy(f'{root_folder}/Molecule/{reactant_molecule}/OUTCAR_{dft_xc}.gz', code='vasp')
                reactant_surface_energy = (1/3)*get_energy(f'{root_folder}/Molecule-Surface/4L_O-Pt_fcc_111_{sc_size}/OUTCAR_{dft_xc}.gz', code='vasp')  - (1/9)*get_energy(f'{root_folder}/Surface/4L_Pt_fcc_111_{sc_size}/OUTCAR_{dft_xc}.gz', code='vasp') 
                ce39_dft_xc_eads_dict[ce39_idx][dft_xc] = (2 / 9 * total_product_energy - reactant_molecule_energy - reactant_surface_energy) * 1000 / kjmol_to_meV + ce39_eads_dict[ce39_idx]['BEEFvdW (6L)'] - ce39_eads_dict[ce39_idx]['BEEFvdW (4L)']

            ce39_dft_xc_eads_dict[ce39_idx]['Experiment'] = ce39_dataset_dict[ce39_idx]['Reaction Energy without ZPE']
            ce39_dft_xc_eads_dict[ce39_idx]['Reaction'] = ce39_dataset_dict[ce39_idx]['Reaction']
        except:
            print(f"Error processing reaction {ce39_idx}: {ce39_dataset_dict[ce39_idx]['Reaction']}")
            continue

metrics_methods = ['RPA', 'RPA_beef', 'RPA+rSE',  'RPA+EXX75', 'BEEFvdW', 'hBEEFvdW', 'dhBEEFvdW'] + dft_xc_list

# Add DFT XC results to final_ce39_eads_df
ce39_dft_xc_eads_df = pd.DataFrame.from_dict(ce39_dft_xc_eads_dict, orient='index')
# Round to nearest integer and convert to integer
ce39_dft_xc_eads_df = ce39_dft_xc_eads_df.round(0).astype({dft_xc: 'Int64' for dft_xc in dft_xc_list} | {'Experiment': 'Int64', 'Reaction': str})
final_ce39_eads_df = pd.concat([final_ce39_eads_df, ce39_dft_xc_eads_df[dft_xc_list]], axis=1)

# MAD
mad_dict_final = {m: np.mean(np.abs(final_ce39_eads_df[m] - final_ce39_eads_df['Experiment'])) for m in metrics_methods}
final_ce39_eads_df.loc['MAD'] = ['MAD', 0] + [mad_dict_final[m] for m in metrics_methods]

# weighted MAD
wmad_dict_final = {m: np.mean(np.abs(final_ce39_eads_df[m] - final_ce39_eads_df['Experiment']) * ce39_dataset_df['MAD Weight']) for m in metrics_methods}
final_ce39_eads_df.loc['wMAD'] = ['wMAD', 0] + [wmad_dict_final[m] for m in metrics_methods]

# RMSD
rmsd_dict_final = {m: np.sqrt(np.mean((final_ce39_eads_df[m] - final_ce39_eads_df['Experiment'])**2)) for m in metrics_methods}
final_ce39_eads_df.loc['RMSD'] = ['RMSD', 0] + [rmsd_dict_final[m] for m in metrics_methods]

# weighted RMSD
rmsd_w_dict_final = {m: np.sqrt(np.mean(((final_ce39_eads_df[m] - final_ce39_eads_df['Experiment'])**2) * ce39_dataset_df['MAD Weight'])) for m in metrics_methods}
final_ce39_eads_df.loc['wRMSD'] = ['wRMSD', 0] + [rmsd_w_dict_final[m] for m in metrics_methods]

# Round and cast
astype_map = {'Experiment': 'Int64', 'Reaction': str}
astype_map.update({m: 'Int64' for m in metrics_methods})
final_ce39_eads_df = final_ce39_eads_df.round(0).astype(astype_map)

display(final_ce39_eads_df)

# Combine final_ce39_eads_dict and ce39_dft_xc_eads_dict
final_ce39_eads_dict = {ce39_idx: final_ce39_eads_dict[ce39_idx] | {dft_xc: ce39_dft_xc_eads_dict[ce39_idx][dft_xc] for dft_xc in dft_xc_list} for ce39_idx in ce39_dataset_dict}